package foo:foo;

/// regular comment
///#[derive(Serialize, Deserialize)]
///@unstable
interface strings {
  a: func(x: string);
  b: func() -> string;
  c: func(a: string, b: string) -> string;
}

///@unstable(feature = foo)
world the-world {
  import strings;
  export strings;
}
