package a:b@0.1.0;

interface foo {

  #rust(derive = "Serialize, Deserialize")  // #[derive(Serialize, Deserialize)
  #rust(derive = "Debug")                   // #[derive(Debug)
  #python(decorate = "pyserde")             // @pyserde
  #rust(serde = `rename_all = “camelCase”`)
  #whatever()
  x: func(y: string);
}

world bar {
  export foo;

}
