package foo:foo;

///unstable
///(serde=Serialize,serde=Deserialize)
interface strings {
  a: func(x: string);
  /// (six = seven, max = gordon, sarayu = vijayanagaram)
  b: func() -> string;
  c: func(a: string, b: string) -> string;
}

///unstable
world the-world {
  import strings;
  export strings;
}
