package foo:foo;

#unstable
#(serde=Serialize,serde=Deserialize)
interface strings {
  a: func(x: string);
  # annotation with spaces
  b: func() -> string;
  c: func(a: string, b: string) -> string;
}

#unstable
# testing a quote
world the-world {
  import strings;
  export strings;
}
